### ISSUE TITLE
✖ ERROR: helpers.handleFiles is not a function

### ISSUE THREAD

**Issue by artemave** [jprichardson/electron-mocha#145]
Hello,

I have started getting this error with the latest mocha (v6.2.0):

```
✖ ERROR: helpers.handleFiles is not a function
```

Looks like mocha integration is out of sync?

**Comment by inukshuk** [comment]
You're right, this should be fixed with 8.1.0 which will work with mocha 6.2 (current release will only work with 6.1)
