### ISSUE TITLE
Friction with ts-mocha when upgrading to 11.0.0

### ISSUE THREAD

**Issue by JJ** [jprichardson/electron-mocha#191]
I'm using this command-line to test:

```
electron-mocha --renderer --require ts-node/register src/tests/electron/*.test.ts
```

This fails with:

```
ERROR: Cannot find module '/path/to/ts-node/register'
Require stack:
- /path/to/node_modules/electron-mocha/lib/mocha.js
- /path/to/node_modules/electron-mocha/renderer/run.js
```

I have installed ts-node, to no avail. This is using TS 4.4, mocha 9.0 and latest version of ts-mocha, 8.0

**Comment by inukshuk** [comment]
Thanks, should be fixed in 11.0.1
